### ISSUE TITLE
Local inference and class inheritance bug

### ISSUE THREAD

**Issue by lthls** [ocaml-flambda/ocaml-jst#65]
The opam package `mm` fails to build with the flambda-backend compilers, with a type error.
I managed to create a small example and reproduce the issue with the `ocaml-jst` repo, so I'm creating an issue here.

The small example has two files, `dep.ml` and `main.ml` (no mli files).
`Dep` contains class definitions:
```ocaml
class c =
  object
    method private m () () = 0
  end

class virtual cv =
  object
    method virtual private m : unit -> unit -> int
  end
```
`Main` contains one class inheriting from those:
```ocaml
class c fname =
  object
    inherit Dep.c
    inherit Dep.cv
  end
```
Then compiling `main.ml` (after compiling `dep.ml`) yields the following error:
```
4 |     inherit Dep.cv
        ^^^^^^^^^^^^^^
Error: The method m has type unit -> unit -> int but is expected to have type
         unit -> local_ (unit -> int)
       Type unit -> unit -> int is not compatible with type
         unit -> local_ (unit -> int) 
```

**Comment by lpw25** [comment]
Looks like we lost [this call to `Ctype.remove_mode_variables`](https://github.com/ocaml-flambda/ocaml-jst/blob/05e2ed4cdd914fb1203a05aab9188f7afa2c506e/typing/typeclass.ml#L218) in the 4.14 rebase.
