### ISSUE TITLE
parser change to "let" desugaring not quite right yet

### ISSUE THREAD

**Issue by ceastlund** [ocaml-flambda/ocaml-jst#83]
The form `let x : t = e` desugars to `let (x : t) = (e : t)`. Prior to 4.14, both type constraints (on the pattern and on the expression) had `loc_ghost=true`. In 4.14, now `(x : t)` has `loc_ghost=true` and `(e : t)` has `loc_ghost=false`.

I think this is a step forward, in that yes, one occurrence of the type constraint should be annotated as "real" syntax, for purposes of merlin and so forth. But it seems like `(x : t)` should have `loc_ghost=false` instead, and `(e : t)` should have `loc_ghost=true`. The type constraint originally appears next to the pattern, so that seems clearly the "real" occurrence, and the locations will line up better that way.

cc @lpw25

**Comment by ceastlund** [comment]
In fact, I think not only should `(e :  t)` have `loc_ghost=true`, I think it would be best if that second occurrence of `t` had `loc_ghost=true` on all of its locations.

**Comment by ccasin** [comment]
FWIW, it looks like the 4.14 change was introduced here:

https://github.com/ocaml/ocaml/pull/10555

The change was motivated by type annotations in records (the helper function `mkexp_constraint`, where the "ghost" flag was turned off, is shared with the let binding code).  Even in the record case, I'm a bit surprised by their choices in terms of what to make ghost and what not, but I suppose I am missing some context.

**Comment by ccasin** [comment]
OK, staring a little at the discussion, I think I understand their motivation.  The key example seems to be `{ lbl : ty }` a punned record expression with a type annotation, which gets parsed as something like `{ lbl = lbl : ty }`.  I guess I can see why here it makes sense for the RHS to be non-ghost and the LHS to be ghost.  They seemed to want patterns and expressions to be parsed consistently, leading to the behavior you observed.  Maybe that's a mistake.

**Comment by ceastlund** [comment]
Why is that different from anything else? The pattern is a punned record, too.

**Comment by ccasin** [comment]
Sorry - I don't understand your question.

To be clear, I think the change you want sounds reasonable.  My comments above were just trying to work out what the change to the parser in 4.14 was, considering it seems like obviously the wrong choice for which part of an annotated let binding should be marked "ghost", as you observe.

**Comment by ceastlund** [comment]
Ah, got it. I had misunderstood what you were saying, then.

**Comment by ncik-roberts** [comment]
I'm closing this as `let x : t = e` no longer desugars to anything in the 5.1 parsetree &mdash; it has its own dedicated encoding, via `Pvc_constraint`. So, there's no longer any node that should be marked ghost. (Though ppxlib's conversion functions between 5.1 and 4.14 might reintroduce a ghost node. But that's solved by migrating ppxlib to 5.1.)
